<p><a href="/employee/form">добавить сотрудника</a></p>

<p>
    <a href="/employee/list">все</a> |
    <a href="/employee/list/<?= Table_User::STATUS_ACTIVE ?>">работающие</a> |
    <a href="/employee/list/<?= Table_User::STATUS_RETIRED ?>">бывшие сотрудники</a> |
    <a href="/employee/list/<?= Table_User::STATUS_TRIAL ?>">на испытательном сроке</a>
</p>

<? if (count($this->users)) { ?>
<table class="stripedTable">
    <?= $this->partialLoop('partials/userRow.phtml', $this->users) ?>
</table>
<? } ?>

<div class="confirm">
    <a href="#" class="yes">да</a>
    <a href="#" class="no">отмена</a>
</div>