<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headScript(); ?>
    </head>

    <body>
        <div class="topArea">
            <p>Привет, <b><?= $this->identity() ?></b></p>
            [ <a href="/logout">выход</a> ]
        </div>

        <div class="main">
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>