<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headScript(); ?>
    </head>

    <body>
        <div class="topArea">
            <p>
                <b><?= $this->identity() ?></b>
                [ <a href="/logout">выход</a> ]<br/>
                <small><a href="/profile/edit">редактировать профиль</a></small>
            </p>
            <?= $this->navigation($this->navConfig); ?>
        </div>

        <div class="main">
            <h1><?= $this->getHelper('Navigation')->headline(); ?></h1>
            <?= $this->layout()->content; ?>
        </div>
    </body>
</html>