<?php

/**
 * Table_Base_Access
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rule_id
 * @property integer $role_id
 * @property Table_Rule $Rules
 * @property Table_Role $Roles
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Table_Base_Access extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('sys_access');
        $this->hasColumn('rule_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Table_Rule as Rules', array(
             'local' => 'rule_id',
             'foreign' => 'id'));

        $this->hasOne('Table_Role as Roles', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}