<?php

/**
 * Table_Base_Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role
 * @property string $resource
 * @property Table_Role $Role
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Table_Base_Permission extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('sys_permissions');
        $this->hasColumn('role', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('resource', 'string', 50, array(
             'type' => 'string',
             'primary' => true,
             'length' => '50',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Table_Role as Role', array(
             'local' => 'role',
             'foreign' => 'id'));
    }
}