<?php

/**
 * Table_Base_Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $description
 * @property integer $rule
 * @property Table_Rule $Rule
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Table_Base_Resource extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('sys_resources');
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('rule', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Table_Rule as Rule', array(
             'local' => 'rule',
             'foreign' => 'id'));
    }
}