<tr>
    <td width="200">
        <a href="/admin/employee/<?= $this->login ?>">
            <?= $this->lastname ?>&nbsp;<?= $this->firstname ?>
        </a>
    </td>
    <td>
        <?= $this->Role['name'] ?>
    </td>
    <td width="60">
        <? if ($this->login != Zend_Auth::getInstance()->getIdentity()->login) { ?>
            <a href="/admin/delemployee/<?= $this->login ?>" class="delete">удалить</a>
        <? } ?>
    </td>
</tr>